Windows 14.

diff --git a/.github/workflows/package-build.yml b/.github/workflows/package-build.yml
--- a/.github/workflows/package-build.yml
+++ b/.github/workflows/package-build.yml
@@ -59,6 +59,14 @@ jobs:
       fail-fast: false
     steps:
     - uses: actions/checkout@v3
+    - name: msys setup
+      shell: 'C:/shells/msys2bash.cmd {0}'
+      run: |
+        set -euo pipefail
+        pwd
+        echo "TODO install missing msys packages"
+        cat "/C/shells/msys2bash.cmd"
+        # make
     - name: build windows ouptuts
       shell: cmd
       run: |
@@ -67,12 +75,7 @@ jobs:
         where cl
         type C:/shells/msys2bash.cmd
         C:/shells/msys2bash.cmd -use-full-path "./scripts/build_win.sh"
-    - name: msys setup
-      shell: 'C:/shells/msys2bash.cmd {0}'
-      run: |
-        set -euo pipefail
-        echo "TODO install missing msys packages"
-        # make
+
     - name: set windows outputs
       shell: bash
       run: |
